out_dir: 'debug_model_3K_new'
eval_interval: 50  # how often to evaluate against the validation set
eval_iters_train: 50
eval_iters_val: 50
log_interval: 1  # how often to print to the console (1 = every iteration)
init_from: 'scratch'
device: 'cuda'
compile: True
gradient_accumulation_steps: 40  # used to simulate larger batch sizes

dtype: 'float16'

# whether to always save a checkpoint
always_save_checkpoint: True

# whether to validate with a validation set
validate: True

dataset: 'dataset/CHILI-3K/'
batch_size: 16
block_size: 512

n_layer: 4
n_head: 4
n_embd: 64
dropout: 0.0

learning_rate: 1e-3
max_iters: 200000
lr_decay_iters: 200000
min_lr: 1e-4
beta2: 0.99

warmup_iters: 100
