out_dir: '../experiments/CrystaLLM/scratch/conditioned_prefix/small_C-100'
eval_interval: 1000  # how often to evaluate against the validation set
eval_iters_train: 200
eval_iters_val: 200
log_interval: 1  # how often to print to the console (1 = every iteration)
init_from: 'scratch'

device: 'cuda'
compile: True

dtype: 'float16'

# whether to always save a checkpoint
always_save_checkpoint: True

# whether to validate with a validation set
validate: True

dataset: '../data/CrystaLLM/datasets/conditioned_prefix_100'
batch_size: 16
block_size: 512

n_layer: 2
n_head: 2
n_embd: 128
dropout: 0.1

learning_rate: 1e-3
max_iters: 100_000
lr_decay_iters: 100_000
min_lr: 1e-4
beta2: 0.99

warmup_iters: 100

early_stopping_patience: 5

validate_generation: True
validate_generation_start_iter: 100
gen_iters_train: 1
gen_iters_val: 1
gen_max_new_tokens: 500
gen_top_k: 10
gen_batch_size: 2
