out_dir: 'crystallm_v1_small_debug_finetune_100K_empty'
eval_interval: 10  # how often to evaluate against the validation set
eval_iters_train: 10
eval_iters_val: 10
log_interval: 1  # how often to print to the console (1 = every iteration)
init_from: 'finetune'
device: 'cuda'
compile: True
gradient_accumulation_steps: 40

dtype: 'float16'

# whether to always save a checkpoint
always_save_checkpoint: True

# whether to validate with a validation set
validate: True

dataset: 'dataset/100K-empty'
batch_size: 32
block_size: 1024

n_layer: 8
n_head: 8
n_embd: 512
dropout: 0.0

learning_rate: 1e-3
max_iters: 200000
lr_decay_iters: 200000
min_lr: 1e-4
beta2: 0.99

warmup_iters: 100
